name: CI

on:
  push:
    branches:
      - master # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t username/my-app:${{ github.sha }} .
          docker tag username/my-app:${{ github.sha }} username/my-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push username/my-app:latest
          docker push username/my-app:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker pull username/my-app:${{ github.sha }}
            docker stop my-app || true  
            docker rm my-app || true   
            docker run -d --name my-app -p 8081:8081 username/my-app:${{ github.sha }}

